//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.05 at 11:29:35 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.nitish.JAXB.IMCS_JAXB;
